services:
    marttiphpbb.showforumsubscribers.listener:
        class: marttiphpbb\showforumsubscribers\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@marttiphpbb.showforumsubscribers.forum_subscribers'
        tags:
            - { name: event.listener }

    marttiphpbb.showforumsubscribers.forum_subscribers:
        class: marttiphpbb\showforumsubscribers\service\forum_subscribers
        arguments:
            - '@dbal.conn'
            - '%tables.forums_watch%'
            - '%tables.users%'